Refactor to use Mdbook and introductio
mun-lang/book pull request #4
Opened 2019-09-17 12:47 UTC by baszalmstra

2019-09-17 21:08 UTC, Wodann requested changes

2019-09-17 21:08 UTC, Wodann commented on book.toml
> +authors = ["Bas Zalmstra"]
```suggestion
authors = ["Bas Zalmstra", "Remco Kuijper"]
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +* **Ahead of time compiled**
```suggestion
* **Ahead of time compilation**
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  Mun is ahead of time (AOT) compiled instead of interpreted or JITed. This
```suggestion
  Mun is compiled ahead of time (AOT), as opposed to being interpreted or compiled just in time (JIT).
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  enables catching a lot of errors at compile time instead of at runtime. AOT
```suggestion
  By detecting type errors during AOT compilation, an entire class of runtime errors is eliminated.
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  compilation allows developers to stay in their IDE instead of having to debug
```suggestion
  Whereas developers of interpreted or JIT compiled languages have to constantly switch between their IDE and target application to debug runtime errors, an AOT compiled language allows developers to stay within the comfort of their IDE.
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +* **Ahead of time compiled**
Maybe add something along the lines of:

```
AOT compilation results in machine code that can be natively executed on a platform,
guaranteeing the best possible performance. Interpreted languages suffer a runtime
penalty as every bytecode instruction needs to be translated to an equivalent machine
code instruction. JIT compiled languages try to overcome this performance deficiency
by optimising their program during an extra runtime compilation.
```

to show that AOT has performance benefits.

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +* **Ahead of time compiled**
We could also add that some platforms don't allow for JIT compilation as they prevent write access to executable memory.

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  Mun uses types that are resolved at compilation time instead of at runtime.
```suggestion
  Mun resolves types at compilation time instead of at runtime, resulting in
  immediate feedback when writing code and opening the door for powerful
  refactoring tools.
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  This enables powerful refactoring tools and better error detection at the time
```suggestion
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  of writing the code vs running the code.
```suggestion
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  Mun is written from the ground up with hot-reloading in mind. Hot-reloading
```suggestion
  Every aspect of Mun is designed with hot reloading in mind. Hot reloading is the
  process of changing code and resources of a live application, removing the need
  to start, stop and recompile an application whenever a function or value needs to
  be changed.```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  enables developers to alter the code while its executing. There no longer is a
```suggestion
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  need to start/stop the application, changing functions, values or classes take
```suggestion
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  effect instantly without restarting the target application.
```suggestion
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  Mun compiles the code to optimized machine code using LLVM. Together with
```suggestion
  Mun compiles code to optimized machine code using LLVM. In combination with
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  static typing this enables native performance. Hot-reloading is enabled by
```suggestion
  static typing this guarantees native runtime performance. Hot reloading does
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  default which adds a little bit of overhead at runtime, however, for
```suggestion
  introduce a slight runtime overhead, but it can be disabled for production
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  production builds hot-reloading can also be turned off which removes all
```suggestion
  builds to ensure the best possible runtime performance.
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  overhead.
```suggestion
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  The Mun language and compiler framework are designed from the ground up to
```suggestion
  The Mun language and compiler framework are designed to
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  The Mun language and compiler framework are designed from the ground up to
From the ground up is a separate statement, and as such its meaning doesn't work as a lead up: https://idioms.thefreedictionary.com/from+the+ground+up

2019-09-17 21:08 UTC, Wodann commented on src/ch00-00-introduction.md
> +  support queries on the source code which enable powerful IDE integration like
```suggestion
  support source code queries, allowing for powerful IDE integrations such as
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-01-case-studio-abbey-games.md
> +Here are some of the case studies that inform the design choices made in Mun.
```suggestion
A collection of case studies that inspired the design choices made in Mun.
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-01-case-studio-abbey-games.md
> +reduce complexity in our code base but would also introduce *magic* or custom
```suggestion
reduce complexity in our code base, but would also introduce *magic* or custom
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-01-case-studio-abbey-games.md
> +Abbey Games keywords which are foreign to both new developers and IDE's.
```suggestion
keywords that are foreign to both new developers and IDE's. 
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-01-case-studio-abbey-games.md
> +live reload the code. This enables very rapid iteration of game code enabling
```suggestion
ability to hot reload code. This allows for very rapid iteration of game code, enabling
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-01-case-studio-abbey-games.md
> +game programmers & designers alike to quickly test and tweak systems and
```suggestion
gameplay programmers and designers to quickly test and tweak systems and
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-01-case-studio-abbey-games.md
> +content. Lua however, is a dynamically typed, Just-in-time compiled language,
```suggestion
content. Lua is a dynamically typed, JIT compiled language. Although this has
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-01-case-studio-abbey-games.md
> +although this has some definite advantages it also introduces a lot of problems
```suggestion
some definite advantages, it also introduces a lot of problems with bigger codebases.
```

2019-09-17 21:08 UTC, Wodann commented on src/ch00-01-case-studio-abbey-games.md
> +with a bigger codebase.
```suggestion
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +Mun is a statically typed languages which helps to detect type-related errors in
```suggestion
Mun is a statically typed language, which helps to detect type-related errors at
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +a program at compile-time. A type error is an invalid operation on a given type
```suggestion
compile-time. A type error is an invalid operation on a given type, such as an
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +such as a division by a string, trying to access a field that doesn't exist or
```suggestion
integer divided by a string, trying to access a field that doesn't exist, or
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +int foo = 3+4;
```suggestion
int foo = 3 + 4;
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +Often the types of variables can be inferred by their usage just as in the
```suggestion
However, often variable types can be inferred by their usage, as illustrated
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +example above. Mun uses type inferencing to determine the type of a variable at
```suggestion
above. Mun uses type inferencing to determine variable types at compile time.
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +compile time. However, it does force you to explicitly annotate variables in a
```suggestion
You are still forced to explicitly annotate variables in a few locations to ensure
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +few locations to ensure a contract between interdependent code.
```suggestion
a contract between interdependent code.
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +    let foo = 3+a
```suggestion
    let foo = 3 + a
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +the function. However, the type of `foo` can be inferred through it's usage.
```suggestion
the function. The type of `foo` can be inferred through its usage.
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +In Mun an `int` can be explicitly casted to `float` but the reverse is not true:
```suggestion
In Mun an `int` can be explicitly cast to `float`, but the reverse is not true.
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +assigning a `float` to an `int` might cause loss of precision and is therefor
```suggestion
Assigning a `float` to an `int` might cause loss of precision and can therefore
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +In Mun an `int` can be explicitly casted to `float` but the reverse is not true:
Do you mean `implicitly cast`? Otherwise the next line should be changed to read `and can therefore not be cast explicitly`.

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +not allowed implicitly.
```suggestion
not be cast implicitly.
```

2019-09-17 21:08 UTC, Wodann commented on src/ch01-00-types.md
> +not allowed implicitly.
`implicit` or `explicit`?

2019-09-17 21:08 UTC, Wodann commented on src/ch02-00-types.md
> +# Types
Is this file not a copy of chapter 1?

2019-09-17 22:05 UTC, baszalmstra commented on src/ch02-00-types.md
> +# Types
Yes, it should not be here.

2019-09-17 22:11 UTC, baszalmstra commented on src/ch00-00-introduction.md
> +* **Ahead of time compiled**
I think that should be covered in the Performance section in that case.

2019-09-17 22:36 UTC, baszalmstra commented
I incorporated most of your changes @Wodann , except for "We could also add that some platforms don't allow for JIT compilation as they prevent write access to executable memory." This would answer the question why not use JIT'ing at runtime. AOT could still be combined with JIT (see typescript for example). However, I don't think we have to answer this question in the introduction so I choose to omit it.

I also moved some stuff from AOT to Performance. 

An new look at the changes would be appreciated! :)

2019-09-18 08:01 UTC, Wodann requested changes

2019-09-18 08:01 UTC, Wodann commented on src/ch00-00-introduction.md
> +*Mun* is an embedable scripting language designed for developer productivity.
```suggestion
*Mun* is an embeddable scripting language designed for developer productivity. 
```

2019-09-18 08:01 UTC, Wodann commented on src/ch00-00-introduction.md
> +  needs to be changed.
```suggestion
  is changed.
```

2019-09-18 08:01 UTC, Wodann commented on src/ch00-00-introduction.md
> +  Mun compiles code to optimized machine code using LLVM. Mun's AOT compilation
```suggestion
  AOT compilation combined with static typing ensure that Mun is compiled to machine code
```

2019-09-18 08:01 UTC, Wodann commented on src/ch00-00-introduction.md
> +  and static typing result in machine code that can be natively executed on a
```suggestion
  that can be natively executed on any target platform. LLVM is used for compilation
```

2019-09-18 08:01 UTC, Wodann commented on src/ch00-00-introduction.md
> +  platform, guaranteeing the best possible performance. Hot reloading does
```suggestion
  and optimization, guaranteeing the best possible performance. Hot reloading does
```

2019-09-18 08:01 UTC, Wodann commented on src/ch00-01-case-studio-abbey-games.md
> +ability to hot reload code. This allows for very rapid iteration of game code,
```suggestion
ability to hot reload code. This allows for rapid iteration of game code,
```

2019-09-18 09:49 UTC, Wodann approved these changes

2019-09-18 09:50 UTC, merged